version: '3'
services:
  prestodb:
    hostname: prestodb
    container_name: prestodb
    image: ahanaio/prestodb-sandbox:latest
    ports:
      - "8080:8080"
    volumes:
      #- ./conf/standalone:/opt/presto/etc:ro
      - ./data:/data
    restart: unless-stopped
