# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - './dvdrental.tar:/dvdrental.tar'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
